(eval-when-compile    (require 'color-theme))
(defun color-theme-darkgray ()
  "Color theme by Chris McMahan, created 2007-07-25.
Major color groups:
- foreground: NavajoWhite3
- background: #343434
- hl-line:    #404040
- region:     #5d5d5d
- mode-line:  #242424"
  (interactive)
  (color-theme-install
   '(color-theme-darkgray
     ((background-color . "#343434")
      (background-mode . dark)
      (background-toolbar-color . "#bfbfbfbfbfbf")
      (border-color . "black")
      (bottom-toolbar-shadow-color . "#737373737373")
      (cursor-color . "Yellow")
      (foreground-color . "NavajoWhite3")
      (mouse-color . "Grey")
      (senator-eldoc-use-color . t)
      (top-toolbar-shadow-color . "#e6e6e6e6e6e6")
      (vc-annotate-very-old-color . "#0046FF")
      (viper-saved-cursor-color-in-replace-mode . "Red3"))
     ((blank-hspace-face . blank-hspace-face)
      (blank-line-face . blank-line-face)
      (blank-map-face . blank-map-face)
      (blank-space-before-tab-face . blank-space-before-tab-face)
      (blank-space-face . blank-space-face)
      (blank-tab-face . blank-tab-face)
      (blank-trailing-face . blank-trailing-face)
      (display-time-mail-face . mode-line)
      (hl-line-face . hl-line)
      (list-matching-lines-buffer-name-face . bold)
      (list-matching-lines-face . bold)
      (ps-line-number-color . "black")
      (ps-zebra-color . 0.95)
      (rmail-highlight-face . rmail-highlight)
      (view-highlight-face . highlight)
      (vm-highlight-url-face . bold-italic)
      (vm-highlighted-header-face . bold)
      (vm-mime-button-face . gui-button-face)
      (vm-summary-highlight-face . bold)
      (widget-mouse-face . highlight))
     (default ((t (:stipple nil :background "#343434" :foreground "NavajoWhite3" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 120 :width normal))))
     (Buffer-menu-buffer-face ((t (nil))))
     (CUA-global-mark-face ((t (nil))))
     (CUA-rectangle-face ((t (nil))))
     (CUA-rectangle-noselect-face ((t (nil))))
     (bbdb-company ((t (:italic t :slant italic))))
     (bbdb-field-name ((t (nil))))
     (bbdb-field-value ((t (nil))))
     (bbdb-name ((t (:foreground "cyan"))))
     (blank-hspace-face ((t (:background "CadetBlue5" :foreground "Aquamarine3"))))
     (blank-line-face ((t (:background "gray20" :foreground "violet"))))
     (blank-map-face ((t (:bold nil :background "Linen" :foreground "Aquamarine3" :weight normal))))
     (blank-space-before-tab-face ((t (:background "DarkOrange" :foreground "firebrick"))))
     (blank-space-face ((t (:background "LightSlateGray"))))
     (blank-tab-face ((t (:background "LightBlue"))))
     (blank-trailing-face ((t (:bold nil :background "red1" :foreground "yellow" :weight normal))))
     (bold ((t (:bold nil :weight normal))))
     (bold-italic ((t (:foreground "LightSkyBlue3" :italic t :slant italic :weight normal))))
     (border ((t (:background "black"))))
     (border-glyph ((t (nil))))
     (buffer-menu-buffer ((t (:bold nil :weight normal))))
     (button ((t (:underline t))))
     (calendar-today ((t (:underline t))))
     (cmode-bracket-face ((t (nil))))
     (comint-highlight-input ((t (:foreground "Palegreen"))))
     (comint-highlight-prompt ((t (:foreground "cyan"))))
     (comint-input-face ((t (:foreground "deepskyblue"))))
     (company-echo ((t (nil))))
     (company-echo-common ((t (:foreground "cyan"))))
     (company-preview ((t (:background "gray30" :foreground "wheat"))))
     (company-preview-common ((t (:background "gray30" :foreground "cyan"))))
     (company-tooltip ((t (:background "white" :foreground "black"))))
     (company-tooltip-common ((t (:background "white" :foreground "red"))))
     (company-tooltip-common-selection ((t (:background "gray80" :foreground "red"))))
     (company-tooltip-selection ((t (:background "gray80" :foreground "black"))))
     (compilation-info-face ((t (:foreground "Green1"))))
     (compilation-warning-face ((t (:foreground "Orange"))))
     (completions-common-part ((t (:background "#605248" :foreground "NavajoWhite3"))))
     (completions-first-difference ((t (:foreground "cyan2"))))
     (cua-global-mark-face ((t (:background "yellow" :foreground "black"))))
     (cua-rectangle-face ((t (:background "maroon" :foreground "white"))))
     (cua-rectangle-noselect-face ((t (:background "dimgray" :foreground "white"))))
     (cursor ((t (:background "Yellow"))))
     (custom-button ((t (:foreground "MediumSlateBlue" :underline t))))
     (custom-button-mouse ((t (:background "grey80" :foreground "black" :box (:line-width 1 :style released-button)))))
     (custom-button-pressed ((t (:background "lightgrey" :foreground "black" :box (:line-width 2 :style pressed-button)))))
     (custom-button-pressed-unraised ((t (:foreground "violet" :underline t))))
     (custom-button-unraised ((t (:underline t))))
     (custom-changed ((t (nil))))
     (custom-comment ((t (:italic t :background "dim gray" :slant italic))))
     (custom-comment-tag ((t (:foreground "gray80"))))
     (custom-documentation ((t (:foreground "Grey"))))
     (custom-face-tag ((t (nil))))
     (custom-group-tag ((t (:foreground "MediumAquamarine"))))
     (custom-group-tag-1 ((t (nil))))
     (custom-invalid ((t (nil))))
     (custom-link ((t (:foreground "cyan1" :underline t))))
     (custom-modified ((t (nil))))
     (custom-rogue ((t (nil))))
     (custom-saved ((t (nil))))
     (custom-set ((t (nil))))
     (custom-state ((t (:foreground "LightSalmon"))))
     (custom-themed ((t (:background "blue1" :foreground "white"))))
     (custom-variable-button ((t (nil))))
     (custom-variable-tag ((t (:foreground "Aquamarine"))))
     (diary ((t (:foreground "IndianRed"))))
     (diary-anniversary ((t (:foreground "Salmon"))))
     (diary-button ((t (nil))))
     (diary-time ((t (:foreground "Aquamarine" :slant normal))))
     (diff-added-face ((t (nil))))
     (diff-changed-face ((t (nil))))
     (diff-context-face ((t (:foreground "grey50"))))
     (diff-file-header-face ((t (nil))))
     (diff-function-face ((t (:foreground "grey50"))))
     (diff-header-face ((t (:background "grey85"))))
     (diff-hunk-header-face ((t (nil))))
     (diff-index-face ((t (nil))))
     (diff-nonexistent-face ((t (:background "grey70"))))
     (diff-removed-face ((t (nil))))
     (dired-directory ((t (:italic t :foreground "Aquamarine" :slant italic))))
     (dired-face-boring ((t (nil))))
     (dired-face-directory ((t (:foreground "sky blue"))))
     (dired-face-executable ((t (:foreground "green yellow"))))
     (dired-face-flagged ((t (:foreground "tomato"))))
     (dired-face-header ((t (nil))))
     (dired-face-marked ((t (:foreground "light salmon"))))
     (dired-face-permissions ((t (:foreground "aquamarine"))))
     (dired-face-setuid ((t (nil))))
     (dired-face-socket ((t (nil))))
     (dired-face-symlink ((t (nil))))
     (dired-flagged ((t (:foreground "IndianRed"))))
     (dired-header ((t (:italic t :foreground "YellowGreen" :slant italic))))
     (dired-ignored ((t (:italic t :foreground "Palegreen" :slant italic))))
     (dired-mark ((t (nil))))
     (dired-marked ((t (:foreground "IndianRed"))))
     (dired-symlink ((t (:foreground "Salmon"))))
     (dired-warning ((t (nil))))
     (display-time-mail-balloon-enhance-face ((t (:background "orange"))))
     (display-time-mail-balloon-gnus-group-face ((t (:foreground "blue"))))
     (display-time-time-balloon-face ((t (:foreground "red"))))
     (ecb-analyse-bucket-element-face ((t (:height 1.0))))
     (ecb-analyse-bucket-node-face ((t (:height 1.0))))
     (ecb-analyse-face ((t (:background "magenta" :foreground "yellow"))))
     (ecb-analyse-general-face ((t (:height 1.0))))
     (ecb-bucket-node-face ((t (:height 1.0))))
     (ecb-bucket-token-face ((t (nil))))
     (ecb-default-general-face ((t (:height 1.0))))
     (ecb-default-highlight-face ((t (:background "cornflower blue" :foreground "yellow"))))
     (ecb-directories-general-face ((t (:height 1.0))))
     (ecb-directory-face ((t (:background "cornflower blue" :foreground "yellow"))))
     (ecb-directory-not-accessible-face ((t (:foreground "gray60" :height 1.0))))
     (ecb-history-face ((t (:background "cornflower blue" :foreground "yellow"))))
     (ecb-history-general-face ((t (:height 1.0))))
     (ecb-method-face ((t (:background "cornflower blue" :foreground "yellow"))))
     (ecb-method-non-semantic-face ((t (:foreground "brown" :slant normal))))
     (ecb-methods-general-face ((t (:slant normal))))
     (ecb-mode-line-data-face ((t (nil))))
     (ecb-mode-line-prefix-face ((t (:foreground "forestgreen"))))
     (ecb-mode-line-win-nr-face ((t (nil))))
     (ecb-source-face ((t (:background "cornflower blue" :foreground "yellow"))))
     (ecb-source-in-directories-buffer-face ((t (:foreground "medium blue"))))
     (ecb-source-read-only-face ((t (:italic t :slant italic))))
     (ecb-sources-face ((t (nil))))
     (ecb-sources-general-face ((t (:height 1.0))))
     (ecb-tag-header-face ((t (nil))))
     (ecb-token-header-face ((t (:background "cornflower blue" :foreground "yellow"))))
     (ecb-tree-guide-line-face ((t (:foreground "gray" :height 1.0))))
     (ecb-type-tag-class-face ((t (nil))))
     (ecb-type-tag-enum-face ((t (nil))))
     (ecb-type-tag-group-face ((t (:foreground "dim gray"))))
     (ecb-type-tag-interface-face ((t (nil))))
     (ecb-type-tag-struct-face ((t (nil))))
     (ecb-type-tag-typedef-face ((t (nil))))
     (ecb-type-tag-union-face ((t (nil))))
     (ecb-type-token-class-face ((t (nil))))
     (ecb-type-token-enum-face ((t (nil))))
     (ecb-type-token-group-face ((t (:foreground "dimgray"))))
     (ecb-type-token-interface-face ((t (nil))))
     (ecb-type-token-struct-face ((t (nil))))
     (ecb-type-token-typedef-face ((t (nil))))
     (edb-inter-field-face ((t (:foreground "deep sky blue"))))
     (edb-normal-summary-face ((t (:foreground "gold"))))
     (ediff-current-diff-face-A ((t (:background "pale green" :foreground "firebrick"))))
     (ediff-current-diff-face-Ancestor ((t (:background "VioletRed" :foreground "Black"))))
     (ediff-current-diff-face-B ((t (:background "Yellow" :foreground "DarkOrchid"))))
     (ediff-current-diff-face-C ((t (:background "indianred" :foreground "white"))))
     (ediff-even-diff-face-A ((t (:background "light grey" :foreground "Black"))))
     (ediff-even-diff-face-Ancestor ((t (:background "Grey" :foreground "White"))))
     (ediff-even-diff-face-B ((t (:background "Grey" :foreground "White"))))
     (ediff-even-diff-face-C ((t (:background "light grey" :foreground "Black"))))
     (ediff-fine-diff-face-A ((t (:background "sky blue" :foreground "Navy"))))
     (ediff-fine-diff-face-Ancestor ((t (:background "Green" :foreground "Black"))))
     (ediff-fine-diff-face-B ((t (:background "cyan" :foreground "Black"))))
     (ediff-fine-diff-face-C ((t (:background "Turquoise" :foreground "Black"))))
     (ediff-odd-diff-face-A ((t (:background "Grey" :foreground "White"))))
     (ediff-odd-diff-face-Ancestor ((t (:background "light grey" :foreground "Black"))))
     (ediff-odd-diff-face-B ((t (:background "light grey" :foreground "Black"))))
     (ediff-odd-diff-face-C ((t (:background "Grey" :foreground "White"))))
     (eieio-custom-slot-tag-face ((t (:foreground "light blue"))))
     (emacs-wiki-bad-link-face ((t (:foreground "coral" :underline "coral"))))
     (emacs-wiki-header-1 ((t (:height 1.3 :family "helv"))))
     (emacs-wiki-header-2 ((t (:height 1.2 :family "helv"))))
     (emacs-wiki-header-3 ((t (:height 1.1 :family "helv"))))
     (emacs-wiki-header-4 ((t (:height 1.0 :family "helv"))))
     (emacs-wiki-header-5 ((t (:height 0.9 :family "helv"))))
     (emacs-wiki-link-face ((t (:foreground "cyan" :underline "cyan"))))
     (emacs-wiki-verbatim-face ((t (:foreground "gray"))))
     (epa-field-body-face ((t (:italic t :slant italic))))
     (epa-field-name-face ((t (:bold nil :weight normal))))
     (epa-mark-face ((t (:bold nil :foreground "red" :weight normal))))
     (epa-string-face ((t (:foreground "lightyellow"))))
     (epa-validity-disabled-face ((t (:italic t :slant italic))))
     (epa-validity-high-face ((t (:bold nil :weight normal))))
     (epa-validity-low-face ((t (:italic t :slant italic))))
     (epa-validity-medium-face ((t (:italic t :foreground "PaleTurquoise" :slant italic))))
     (escape-glyph ((t (:foreground "cyan"))))
     (eshell-ls-archive-face ((t (:foreground "IndianRed"))))
     (eshell-ls-backup-face ((t (:foreground "Grey"))))
     (eshell-ls-clutter-face ((t (:foreground "DimGray"))))
     (eshell-ls-directory-face ((t (:foreground "MediumSlateBlue"))))
     (eshell-ls-executable-face ((t (:foreground "Coral"))))
     (eshell-ls-missing-face ((t (:foreground "black"))))
     (eshell-ls-picture-face ((t (:foreground "Violet"))))
     (eshell-ls-product-face ((t (:foreground "LightSalmon"))))
     (eshell-ls-readonly-face ((t (:foreground "Aquamarine"))))
     (eshell-ls-special-face ((t (:foreground "Gold"))))
     (eshell-ls-symlink-face ((t (:foreground "White"))))
     (eshell-ls-text-face ((t (:foreground "medium aquamarine"))))
     (eshell-ls-todo-face ((t (:foreground "aquamarine"))))
     (eshell-ls-unreadable-face ((t (:foreground "DimGray"))))
     (eshell-prompt-face ((t (:foreground "powder blue"))))
     (eshell-test-failed-face ((t (nil))))
     (eshell-test-ok-face ((t (nil))))
     (extra-whitespace-face ((t (nil))))
     (file-name-shadow ((t (:foreground "grey70"))))
     (fixed ((t (nil))))
     (fixed-pitch ((t (nil))))
     (flash-paren-face-off ((t (nil))))
     (flash-paren-face-on ((t (nil))))
     (flash-paren-face-region ((t (nil))))
     (font-lock-builtin-face ((t (:foreground "SteelBlue1" :slant normal))))
     (font-lock-comment-delimiter-face ((t (:italic t :foreground "LightSalmon" :slant italic))))
     (font-lock-comment-face ((t (:italic t :foreground "LightSalmon" :slant italic))))
     (font-lock-constant-face ((t (nil))))
     (font-lock-doc-face ((t (:foreground "LightSalmon"))))
     (font-lock-doc-string-face ((t (:foreground "LightSalmon"))))
     (font-lock-emphasized-face ((t (nil))))
     (font-lock-exit-face ((t (nil))))
     (font-lock-function-name-face ((t (:foreground "Aquamarine"))))
     (font-lock-keyword-face ((t (:foreground "Salmon"))))
     (font-lock-negation-char-face ((t (nil))))
     (font-lock-other-emphasized-face ((t (nil))))
     (font-lock-other-type-face ((t (nil))))
     (font-lock-preprocessor-face ((t (:foreground "Salmon"))))
     (font-lock-reference-face ((t (:foreground "pale green"))))
     (font-lock-regexp-grouping-backslash ((t (nil))))
     (font-lock-regexp-grouping-construct ((t (nil))))
     (font-lock-special-comment-face ((t (nil))))
     (font-lock-special-keyword-face ((t (nil))))
     (font-lock-string-face ((t (:foreground "Palegreen" :weight normal))))
     (font-lock-type-face ((t (:foreground "YellowGreen" :weight normal))))
     (font-lock-variable-name-face ((t (:foreground "Aquamarine" :slant normal))))
     (font-lock-warning-face ((t (:foreground "IndianRed"))))
     (fringe ((t (:background "#343434"))))
     (gnu-cite-face-3 ((t (nil))))
     (gnu-cite-face-4 ((t (nil))))
     (gnus-cite-attribution-face ((t (:italic t :slant italic))))
     (gnus-cite-face-1 ((t (:foreground "LightSalmon"))))
     (gnus-cite-face-10 ((t (nil))))
     (gnus-cite-face-11 ((t (nil))))
     (gnus-cite-face-2 ((t (:foreground "Khaki"))))
     (gnus-cite-face-3 ((t (:foreground "Coral"))))
     (gnus-cite-face-4 ((t (:foreground "yellow green"))))
     (gnus-cite-face-5 ((t (:foreground "dark khaki"))))
     (gnus-cite-face-6 ((t (:foreground "bisque"))))
     (gnus-cite-face-7 ((t (:foreground "peru"))))
     (gnus-cite-face-8 ((t (:foreground "light coral"))))
     (gnus-cite-face-9 ((t (:foreground "plum"))))
     (gnus-cite-face-list ((t (nil))))
     (gnus-emphasis-bold ((t (nil))))
     (gnus-emphasis-bold-italic ((t (:italic t :slant italic))))
     (gnus-emphasis-highlight-words ((t (nil))))
     (gnus-emphasis-italic ((t (:italic t :slant italic))))
     (gnus-emphasis-strikethru ((t (nil))))
     (gnus-emphasis-underline ((t (nil))))
     (gnus-emphasis-underline-bold ((t (nil))))
     (gnus-emphasis-underline-bold-italic ((t (:italic t :slant italic))))
     (gnus-emphasis-underline-italic ((t (:italic t :slant italic))))
     (gnus-filterhist-face-1 ((t (nil))))
     (gnus-group-mail-1-empty-face ((t (:bold nil :weight normal :foreground "White"))))
     (gnus-group-mail-1-face ((t (:bold nil :weight normal :foreground "White"))))
     (gnus-group-mail-2-empty-face ((t (:bold nil :weight normal :foreground "light cyan"))))
     (gnus-group-mail-2-face ((t (:bold nil :weight normal :foreground "light cyan"))))
     (gnus-group-mail-3-empty-face ((t (:bold nil :weight normal :foreground "LightBlue"))))
     (gnus-group-mail-3-face ((t (:bold nil :weight normal :foreground "LightBlue"))))
     (gnus-group-mail-low-empty-face ((t (:bold nil :weight normal :foreground "Aquamarine"))))
     (gnus-group-mail-low-face ((t (:bold nil :weight normal :foreground "Aquamarine"))))
     (gnus-group-news-1-empty-face ((t (:bold nil :weight normal :foreground "Gray70"))))
     (gnus-group-news-1-face ((t (:bold nil :weight normal :foreground "Navajo White"))))
     (gnus-group-news-2-empty-face ((t (:bold nil :weight normal :foreground "Gray70"))))
     (gnus-group-news-2-face ((t (:bold nil :weight normal :foreground "Navajo White"))))
     (gnus-group-news-3 ((t (:bold nil :weight normal :foreground "White"))))
     (gnus-group-news-3-empty-face ((t (:bold nil :weight normal :foreground "Gray70"))))
     (gnus-group-news-3-face ((t (:bold nil :weight normal :foreground "white"))))
     (gnus-group-news-4-empty-face ((t (:bold nil :weight normal :foreground "Gray70"))))
     (gnus-group-news-4-face ((t (:bold nil :weight normal :foreground "Navajo White"))))
     (gnus-group-news-5-empty-face ((t (:bold nil :weight normal :foreground "Gray70"))))
     (gnus-group-news-5-face ((t (:bold nil :weight normal :foreground "Navajo White"))))
     (gnus-group-news-6-empty-face ((t (:bold nil :weight normal :foreground "Gray70"))))
     (gnus-group-news-6-face ((t (:bold nil :weight normal :foreground "Navajo White"))))
     (gnus-group-news-low-empty-face ((t (:bold nil :weight normal :foreground "Gray70"))))
     (gnus-group-news-low-face ((t (:bold nil :weight normal :foreground "Navajo White"))))
     (gnus-header-content-face ((t (:italic t :bold nil :weight normal :foreground "LightSkyBlue3" :slant italic))))
     (gnus-header-from-face ((t (:bold nil :weight normal :foreground "light cyan"))))
     (gnus-header-name-face ((t (:bold nil :weight normal :foreground "LightBlue"))))
     (gnus-header-newsgroups-face ((t (:italic t :bold nil :weight normal :foreground "MediumAquamarine" :slant italic))))
     (gnus-header-subject-face ((t (:bold nil :weight normal :foreground "light cyan"))))
     (gnus-picon-face ((t (:background "white" :foreground "black"))))
     (gnus-picon-xbm-face ((t (:background "white" :foreground "black"))))
     (gnus-picons-face ((t (nil))))
     (gnus-picons-xbm-face ((t (nil))))
     (gnus-server-agent-face ((t (nil))))
     (gnus-server-closed-face ((t (nil))))
     (gnus-server-denied-face ((t (nil))))
     (gnus-server-offline-face ((t (nil))))
     (gnus-server-opened-face ((t (nil))))
     (gnus-signature-face ((t (:italic t :foreground "Grey" :slant italic))))
     (gnus-splash ((t (nil))))
     (gnus-splash-face ((t (:foreground "MediumAquamarine"))))
     (gnus-summary-cancelled-face ((t (:background "Black" :foreground "Yellow"))))
     (gnus-summary-high-ancient-face ((t (:foreground "MediumAquamarine"))))
     (gnus-summary-high-read-face ((t (:foreground "Aquamarine"))))
     (gnus-summary-high-ticked-face ((t (:foreground "LightSalmon"))))
     (gnus-summary-high-undownloaded-face ((t (nil))))
     (gnus-summary-high-unread-face ((t (:italic t :foreground "beige" :slant italic))))
     (gnus-summary-low-ancient-face ((t (:italic t :foreground "DimGray" :slant italic))))
     (gnus-summary-low-read-face ((t (:italic t :foreground "slate gray" :slant italic))))
     (gnus-summary-low-ticked-face ((t (:italic t :foreground "Pink" :slant italic))))
     (gnus-summary-low-undownloaded-face ((t (nil))))
     (gnus-summary-low-unread-face ((t (:italic t :foreground "LightGray" :slant italic))))
     (gnus-summary-normal-ancient-face ((t (:foreground "MediumAquamarine"))))
     (gnus-summary-normal-read-face ((t (:foreground "Aquamarine"))))
     (gnus-summary-normal-ticked-face ((t (:foreground "LightSalmon"))))
     (gnus-summary-normal-undownloaded-face ((t (nil))))
     (gnus-summary-normal-unread-face ((t (nil))))
     (gnus-summary-selected-face ((t (:underline t))))
     (gnus-x-face ((t (nil))))
     (gui-button-face ((t (:background "darkred"))))
     (gui-element ((t (nil))))
     (header-line ((t (:background "grey20" :foreground "grey90" :box nil))))
     (help-argument-name ((t (:italic t :slant italic))))
     (highlight ((t (:background "#404040"))))
     (highlight-changes-delete-face ((t (nil))))
     (highlight-changes-face ((t (nil))))
     (highline-face ((t (:background "#404040"))))
     (highline-vertical-face ((t (:background "white"))))
     (hl-line ((t (:background "#404040"))))
     (holiday ((t (:background "DimGray"))))
     (horizontal-divider ((t (nil))))
     (hproperty:but-face ((t (nil))))
     (hproperty:flash-face ((t (nil))))
     (hproperty:highlight-face ((t (nil))))
     (hproperty:item-face ((t (nil))))
     (html-helper-bold-face ((t (nil))))
     (html-helper-bold-italic-face ((t (nil))))
     (html-helper-builtin-face ((t (:foreground "blue3" :underline t))))
     (html-helper-italic-face ((t (:foreground "yellow"))))
     (html-helper-underline-face ((t (:underline t))))
     (html-tag-face ((t (:foreground "Blue"))))
     (info-header-node ((t (:italic t :foreground "brown" :slant italic))))
     (info-header-xref ((t (:foreground "magenta4"))))
     (info-menu-6 ((t (nil))))
     (info-menu-header ((t (:family "helv"))))
     (info-menu-star ((t (:underline t))))
     (info-node ((t (:italic t :foreground "DodgerBlue1" :underline t :slant italic))))
     (info-title-1 ((t (:weight normal :height 1.728 :family "helv"))))
     (info-title-2 ((t (:weight normal :height 1.44 :family "helv"))))
     (info-title-3 ((t (:weight normal :height 1.2 :family "helv"))))
     (info-title-4 ((t (:weight normal :family "helv"))))
     (info-xref ((t (:foreground "DodgerBlue1"))))
     (info-xref-visited ((t (:foreground "magenta3"))))
     (isearch ((t (:background "DarkSeaGreen3" :foreground "black"))))
     (isearch-secondary ((t (:background "DarkSeaGreen4"))))
     (ispell-face ((t (nil))))
     (italic ((t (:italic t :slant italic))))
     (jde-bug-breakpoint-cursor ((t (:background "brown" :foreground "cyan"))))
     (jde-bug-breakpoint-marker ((t (:background "yellow" :foreground "red"))))
     (jde-db-active-breakpoint-face ((t (:background "red" :foreground "black"))))
     (jde-db-requested-breakpoint-face ((t (:background "yellow" :foreground "black"))))
     (jde-db-spec-breakpoint-face ((t (:background "green" :foreground "black"))))
     (jde-java-font-lock-api-face ((t (:foreground "light goldenrod"))))
     (jde-java-font-lock-bold-face ((t (nil))))
     (jde-java-font-lock-code-face ((t (nil))))
     (jde-java-font-lock-constant-face ((t (:foreground "Aquamarine"))))
     (jde-java-font-lock-doc-tag-face ((t (:foreground "light coral"))))
     (jde-java-font-lock-italic-face ((t (:italic t :slant italic))))
     (jde-java-font-lock-link-face ((t (:foreground "blue" :underline t :slant normal))))
     (jde-java-font-lock-modifier-face ((t (:foreground "LightSteelBlue"))))
     (jde-java-font-lock-number-face ((t (:foreground "LightSalmon"))))
     (jde-java-font-lock-operator-face ((t (:foreground "medium blue"))))
     (jde-java-font-lock-package-face ((t (:foreground "steelblue1"))))
     (jde-java-font-lock-pre-face ((t (nil))))
     (jde-java-font-lock-underline-face ((t (:underline t))))
     (lazy-highlight ((t (:background "DarkSeaGreen4"))))
     (lazy-highlight-face ((t (nil))))
     (linemenu-face ((t (:background "#3a4d5b"))))
     (link ((t (:foreground "cyan1" :underline t))))
     (link-visited ((t (:foreground "violet" :underline t))))
     (list-mode-item-selected ((t (:background "gray68" :foreground "dark green"))))
     (log-view-file-face ((t (:background "grey70"))))
     (log-view-message-face ((t (:background "grey85"))))
     (makefile-space-face ((t (nil))))
     (man-bold ((t (nil))))
     (man-heading ((t (nil))))
     (man-italic ((t (nil))))
     (man-xref ((t (nil))))
     (match ((t (:background "RoyalBlue4"))))
     (menu ((t (:background "systemmenutext" :foreground "systemmenu"))))
     (message-cited-text ((t (nil))))
     (message-header-cc ((t (:foreground "light cyan"))))
     (message-header-contents ((t (:italic t :slant italic))))
     (message-header-name ((t (:foreground "LightBlue"))))
     (message-header-newsgroups ((t (:italic t :foreground "MediumAquamarine" :slant italic))))
     (message-header-other ((t (:foreground "MediumAquamarine"))))
     (message-header-subject ((t (:foreground "light cyan"))))
     (message-header-to ((t (:foreground "light cyan"))))
     (message-header-xheader ((t (:foreground "MediumAquamarine"))))
     (message-headers ((t (nil))))
     (message-highlighted-header-contents ((t (nil))))
     (message-mml ((t (nil))))
     (message-separator ((t (:foreground "chocolate"))))
     (message-url ((t (:foreground "cyan"))))
     (minibuffer-prompt ((t (:foreground "palegreen"))))
     (mode-line ((t (:background "#242424" :foreground "gray75" :box (:line-width -1 :color "gray50" :style nil)))))
;     (mode-line ((t (:background "#242424" :foreground "gray75" :box (:line-width -1 :style released-button)))))
     (mode-line-buffer-id ((t (:bold nil :weight normal))))
     (mode-line-highlight ((t (:box (:line-width 2 :color "grey40" :style released-button)))))
     (mode-line-inactive ((t (:background "#343434" :foreground "grey50" :box (:line-width -1 :color "grey50" :style nil) :weight light))))
     (modeline-mousable ((t (nil))))
     (modeline-mousable-minor-mode ((t (nil))))
     (mouse ((t (:background "black"))))
     (mumamo-background-chunk-major ((t (:background "gray34"))))
     (mumamo-background-chunk-submode ((t (:background "gray34"))))
     (muse-bad-link ((t (:bold nil :foreground "red" :underline "red" :weight normal))))
     (muse-bad-link-face ((t (:foreground "coral" :underline "coral"))))
     (muse-emphasis-1 ((t (:italic t :slant italic))))
     (muse-emphasis-2 ((t (:bold nil :weight normal))))
     (muse-emphasis-3 ((t (:italic t :bold nil :slant italic :weight normal))))
     (muse-header-1 ((t (:bold nil :weight normal :height 1.4 :family "helv"))))
     (muse-header-2 ((t (:bold nil :weight normal :height 1.3 :family "helv"))))
     (muse-header-3 ((t (:bold nil :weight normal :height 1.2 :family "helv"))))
     (muse-header-4 ((t (:bold nil :weight normal :height 1.1 :family "helv"))))
     (muse-header-5 ((t (:bold nil :weight normal :height 1.0 :family "helv"))))
     (muse-link ((t (:bold nil :foreground "cyan" :weight normal))))
     (muse-link-face ((t (:foreground "cyan"))))
     (muse-verbatim ((t (:foreground "gray"))))
     (muse-verbatim-face ((t (:foreground "gray"))))
     (my-summary-highlight-face ((t (:foreground "White"))))
     (my-tab-face ((t (nil))))
     (my-url-face ((t (:foreground "PaleTurquoise"))))
     (newsticker-enclosure-face ((t (:bold t :background "orange" :weight bold))))
     (newsticker-extra-face ((t (:italic t :foreground "gray50" :slant italic :height 0.8))))
     (newsticker-feed-face ((t (:bold t :foreground "misty rose" :weight bold :height 1.2 :family "helvetica"))))
     (newsticker-treeview-face ((t (:foreground "misty rose" :weight normal :family "helvetica"))))
     (newsticker-treeview-immortal-face ((t (:italic t :family "helvetica" :weight normal :foreground "orange" :slant italic))))
     (newsticker-treeview-new-face ((t (:bold t :family "helvetica" :foreground "misty rose" :weight normal))))
     (newsticker-treeview-obsolete-face ((t (:family "helvetica" :weight normal :foreground "misty rose" :strike-through t))))
     (newsticker-treeview-old-face ((t (:family "helvetica" :weight normal :foreground "NavajoWhite3"))))
     (newsticker-treeview-selection-face ((t (:background "##5d5d5d"))))
     (next-error ((t (:background "#5d5d5d"))))
     (nobreak-space ((t (:foreground "cyan" :underline t))))
     (nxml-attribute-colon-face ((t (:foreground "DarkGreen"))))
     (nxml-attribute-local-name-face ((t (:foreground "nil"))))
     (nxml-attribute-prefix-face ((t (:foreground "DarkGreen"))))
     (nxml-attribute-value-delimiter-face ((t (:foreground "nil"))))
     (nxml-attribute-value-face ((t (:foreground "cyan"))))
     (nxml-cdata-section-CDATA-face ((t (:foreground "DarkGreen"))))
     (nxml-cdata-section-content-face ((t (nil))))
     (nxml-cdata-section-delimiter-face ((t (:foreground "#3a4d5b"))))
     (nxml-char-ref-delimiter-face ((t (:foreground "#3a4d5b"))))
     (nxml-char-ref-number-face ((t (:foreground "#3a4d5b"))))
     (nxml-comment-content-face ((t (:italic t :foreground "lightSalmon" :slant italic))))
     (nxml-comment-delimiter-face ((t (:foreground "LightSalmon"))))
     (nxml-delimited-data-face ((t (:foreground "#3A3A7B"))))
     (nxml-delimiter-face ((t (:foreground "#3a4d5b"))))
     (nxml-element-colon-face ((t (:foreground "DarkGreen"))))
     (nxml-element-local-name-face ((t (:foreground "nil"))))
     (nxml-element-prefix-face ((t (:foreground "DarkGreen"))))
     (nxml-entity-ref-delimiter-face ((t (:foreground "#3a4d5b"))))
     (nxml-entity-ref-name-face ((t (:foreground "#3a4d5b"))))
     (nxml-hash-face ((t (:foreground "DarkGreen"))))
     (nxml-markup-declaration-delimiter-face ((t (:foreground "#3a4d5b"))))
     (nxml-name-face ((t (:foreground "DarkGreen"))))
     (nxml-namespace-attribute-colon-face ((t (:foreground "DarkGreen"))))
     (nxml-namespace-attribute-prefix-face ((t (:foreground "DarkGreen"))))
     (nxml-namespace-attribute-value-delimiter-face ((t (:foreground "DarkGreen"))))
     (nxml-namespace-attribute-value-face ((t (:foreground "DarkGreen"))))
     (nxml-namespace-attribute-xmlns-face ((t (:foreground "DarkGreen"))))
     (nxml-processing-instruction-content-face ((t (:foreground "#3A3A7B"))))
     (nxml-processing-instruction-delimiter-face ((t (:foreground "lightGreen"))))
     (nxml-processing-instruction-target-face ((t (:foreground "lightGreen"))))
     (nxml-prolog-keyword-face ((t (:foreground "DarkGreen"))))
     (nxml-prolog-literal-content-face ((t (:foreground "#3A3A7B"))))
     (nxml-prolog-literal-delimiter-face ((t (:foreground "#3a4d5b"))))
     (nxml-ref-face ((t (:foreground "#3a4d5b"))))
     (nxml-tag-delimiter-face ((t (:foreground "nil"))))
     (nxml-tag-slash-face ((t (:foreground "nil"))))
     (nxml-text-face ((t (:foreground "cyan"))))
     (org-column ((t (:background "gray16"))))
     (org-link ((t (:foreground "cyan" :underline nil))))
     (paren-blink-off ((t (nil))))
     (paren-blink-on ((t (:foreground "purple"))))
     (paren-face ((t (nil))))
     (paren-face-match ((t (nil))))
     (paren-face-mismatch ((t (nil))))
     (paren-face-no-match ((t (nil))))
     (paren-match ((t (nil))))
     (paren-mismatch ((t (nil))))
     (paren-mismatch-face ((t (nil))))
     (paren-no-match-face ((t (nil))))
     (planner-cancelled-task-face ((t (:foreground "gray" :strike-through t))))
     (planner-completed-task-face ((t (:foreground "gray60" :strike-through t))))
     (planner-delegated-task-face ((t (:underline t))))
     (planner-high-priority-task-face ((t (:foreground "red"))))
     (planner-in-progress-task-face ((t (:italic t :slant oblique))))
     (planner-low-priority-task-face ((t (:foreground "skyblue"))))
     (planner-medium-priority-task-face ((t (:foreground "PaleGreen"))))
     (planner-note-headline-face ((t (:foreground "white"))))
     (query-replace ((t (:background "DarkSeaGreen3" :foreground "black"))))
     (region ((t (:background "#5d5d5d"))))
     (ruler-mode-column-number-face ((t (nil))))
     (ruler-mode-current-column-face ((t (nil))))
     (ruler-mode-default-face ((t (nil))))
     (ruler-mode-fill-column-face ((t (nil))))
     (ruler-mode-margins-face ((t (nil))))
     (ruler-mode-tab-stop-face ((t (nil))))
     (scroll-bar ((t (:foreground "systemscrollbar"))))
     (secondary-selection ((t (:background "Aquamarine" :foreground "SlateBlue"))))
     (semantic-complete-inline-face ((t (nil))))
     (semantic-decoration-on-private-members-face ((t (:background "#100000"))))
     (semantic-decoration-on-protected-members-face ((t (:background "#000010"))))
     (semantic-dirty-token-face ((t (:background "gray10"))))
     (semantic-highlight-attribute-face-private ((t (nil))))
     (semantic-highlight-attribute-face-protected ((t (nil))))
     (semantic-highlight-edits-face ((t (:background "gray20"))))
     (semantic-intangible-face ((t (nil))))
     (semantic-read-only-face ((t (nil))))
     (semantic-tag-boundary-face ((t (:overline "cyan"))))
     (semantic-tag-highlight-face ((t (:background "#AAAA33"))))
     (semantic-tag-highlight-start-face ((t (:background "#AAAA33"))))
     (semantic-unmatched-syntax-face ((t (:underline "red"))))
     (senator-intangible-face ((t (:foreground "gray75"))))
     (senator-momentary-highlight-face ((t (:background "#3a4d5b"))))
     (senator-read-only-face ((t (:background "#664444"))))
     (setnu-line-number-face ((t (:italic t :slant italic))))
     (sgml-comment-face ((t (:foreground "dark turquoise"))))
     (sgml-doctype-face ((t (:foreground "red"))))
     (sgml-end-tag-face ((t (:foreground "lightblue"))))
     (sgml-entity-face ((t (:foreground "magenta"))))
     (sgml-ignored-face ((t (:background "gray60" :foreground "gray40"))))
     (sgml-ms-end-face ((t (:foreground "green"))))
     (sgml-ms-start-face ((t (:foreground "yellow"))))
     (sgml-namespace-face ((t (:foreground "SteelBlue1" :slant normal))))
     (sgml-pi-face ((t (:foreground "lime green"))))
     (sgml-sgml-face ((t (:foreground "orange"))))
     (sgml-short-ref-face ((t (:foreground "cyan3"))))
     (sgml-shortref-face ((t (:foreground "gray40"))))
     (sgml-start-tag-face ((t (:foreground "cyan3"))))
     (shadow ((t (:foreground "grey70"))))
     (shell-input-face ((t (nil))))
     (shell-option-face ((t (:foreground "blue4"))))
     (shell-output-2-face ((t (:foreground "green4"))))
     (shell-output-3-face ((t (:foreground "green4"))))
     (shell-output-face ((t (nil))))
     (shell-prompt-face ((t (:foreground "red4"))))
     (show-paren-match ((t (:background "Aquamarine" :foreground "steel blue"))))
     (show-paren-mismatch ((t (:background "Red" :foreground "White"))))
     (show-tabs-space-face ((t (:foreground "yellow"))))
     (show-tabs-tab-face ((t (:foreground "red"))))
     (show-trailing-whitespace ((t (nil))))
     (speedbar-button-face ((t (nil))))
     (speedbar-directory-face ((t (nil))))
     (speedbar-file-face ((t (nil))))
     (speedbar-highlight-face ((t (:background "sea green"))))
     (speedbar-selected-face ((t (:foreground "red" :underline t))))
     (speedbar-separator-face ((t (:background "blue" :foreground "white" :overline "gray"))))
     (speedbar-tag-face ((t (:foreground "yellow"))))
     (template-message-face ((t (nil))))
     (texinfo-heading ((t (:foreground "Aquamarine"))))
     (text-cursor ((t (nil))))
     (tool-bar ((t (:background "systembuttonface" :foreground "systembuttontext" :box (:line-width 1 :style released-button)))))
     (tooltip ((t (:background "systeminfowindow" :foreground "systeminfotext" :family "helv"))))
     (trailing-gray70space ((t (nil))))
     (trailing-gray85space ((t (nil))))
     (trailing-whitespace ((t (:background "red"))))
     (u-vm-color-attribute-face ((t (:foreground "NavajoWhite3" :slant normal))))
     (u-vm-color-author-face ((t (:foreground "NavajoWhite3"))))
     (u-vm-color-citation-1-face ((t (:foreground "LightSalmon"))))
     (u-vm-color-citation-2-face ((t (:foreground "LightSalmon"))))
     (u-vm-color-citation-3-face ((t (:foreground "LightSalmon"))))
     (u-vm-color-citation-4-face ((t (:foreground "LightSalmon"))))
     (u-vm-color-citation-5-face ((t (:foreground "LightSalmon"))))
     (u-vm-color-date-face ((t (:foreground "NavajoWhite3" :slant normal))))
     (u-vm-color-default-face ((t (:italic t :foreground "LightSkyBlue3" :slant italic))))
     (u-vm-color-header-face ((t (:foreground "Gray"))))
     (u-vm-color-id-face ((t (:italic t :foreground "gray" :slant italic))))
     (u-vm-color-label-face ((t (:foreground "NavajoWhite3" :slant normal))))
     (u-vm-color-length-face ((t (:foreground "NavajoWhite3" :slant normal))))
     (u-vm-color-number-face ((t (:foreground "NavajoWhite3" :slant normal))))
     (u-vm-color-recipient-face ((t (:foreground "NavajoWhite3" :slant normal))))
     (u-vm-color-signature-face ((t (:italic t :foreground "Grey" :slant italic))))
     (u-vm-color-spamassassin-face ((t (nil))))
     (u-vm-color-subject-face ((t (:foreground "NavajoWhite3"))))
     (u-vm-color-time-face ((t (:foreground "pink" :slant normal))))
     (u-vm-color-user-face ((t (:foreground "light sea green" :slant normal))))
     (underline ((t (:underline t))))
     (variable-pitch ((t (:family "helv"))))
     (vc-annotate-face-0046FF ((t (:background "black" :foreground "NavajoWhite3"))))
     (vcursor ((t (:background "cyan" :foreground "blue" :underline t))))
     (vertical-border ((t (nil))))
     (vertical-divider ((t (nil))))
     (vvb-face ((t (:background "pink" :foreground "black"))))
     (w3m-anchor-face ((t (:foreground "lightsteelblue2"))))
     (w3m-arrived-anchor-face ((t (:foreground "LightSteelBlue"))))
     (w3m-bold-face ((t (:foreground "LightYellow2"))))
     (w3m-current-anchor-face ((t (:foreground "lightsteelblue" :underline t))))
     (w3m-form-button-face ((t (:background "#5d5d5d" :foreground "NavajoWhite3" :box (:line-width 1 :style released-button)))))
     (w3m-form-button-mouse-face ((t (:background "darkgray" :foreground "black" :box (:line-width 1 :style released-button)))))
     (w3m-form-button-pressed-face ((t (:background "#5d5d5d" :foreground "NavajoWhite3" :box (:line-width 1 :style pressed-button)))))
     (w3m-form-face ((t (:foreground "red" :underline t))))
     (w3m-header-line-location-content-face ((t (:background "Gray20" :foreground "NavajoWhite3"))))
     (w3m-header-line-location-title-face ((t (:background "Gray20" :foreground "beige"))))
     (w3m-history-current-url-face ((t (:background "yellow" :foreground "navy"))))
     (w3m-image-face ((t (:foreground "PaleGreen"))))
     (w3m-insert-face ((t (:foreground "orchid"))))
     (w3m-italic-face ((t (:italic t :slant italic))))
     (w3m-strike-through-face ((t (:strike-through t))))
     (w3m-tab-background-face ((t (:background "LightSteelBlue" :foreground "black" :underline "Gray85"))))
     (w3m-tab-mouse-face ((t (:background "Gray65" :foreground "white" :box (:line-width -1 :style released-button)))))
     (w3m-tab-selected-background-face ((t (:background "LightSteelBlue" :foreground "black"))))
     (w3m-tab-selected-face ((t (:background "Gray85" :foreground "black" :box (:line-width -1 :style released-button) :underline "Gray85"))))
     (w3m-tab-selected-retrieving-face ((t (:background "Gray85" :foreground "red" :box (:line-width -1 :style released-button) :underline "Gray85"))))
     (w3m-tab-unselected-face ((t (:background "Gray50" :foreground "Gray20" :box (:line-width -1 :style released-button) :underline "Gray85"))))
     (w3m-tab-unselected-retrieving-face ((t (:background "Gray50" :foreground "OrangeRed" :box (:line-width -1 :style released-button) :underline "Gray85"))))
     (w3m-underline-face ((t (:underline t))))
     (which-func ((t (:foreground "Blue1"))))
     (which-func-face ((t (:italic t :foreground "Aquamarine" :slant italic))))
     (white ((t (:foreground "white"))))
     (widget ((t (nil))))
     (widget-button ((t (nil))))
     (widget-button-pressed ((t (nil))))
     (widget-documentation ((t (nil))))
     (widget-field ((t (:foreground "LightBlue"))))
     (widget-inactive ((t (:foreground "DimGray"))))
     (widget-single-line-field ((t (:foreground "LightBlue"))))
     (woman-bold ((t (:foreground "cyan"))))
     (xsl-fo-alternate-face ((t (nil))))
     (xsl-fo-main-face ((t (nil))))
     (xsl-other-element-face ((t (nil))))
     (xsl-xslt-alternate-face ((t (nil))))
     (xsl-xslt-main-face ((t (nil))))
     (xxml-emph-1-face ((t (:background "lightyellow"))))
     (xxml-emph-2-face ((t (:background "lightyellow"))))
     (xxml-header-1-face ((t (:background "seashell1" :foreground "MediumAquamarine"))))
     (xxml-header-2-face ((t (:background "seashell1" :foreground "SkyBlue"))))
     (xxml-header-3-face ((t (:background "seashell1"))))
     (xxml-header-4-face ((t (:background "seashell1"))))
     (xxml-interaction-face ((t (:background "lightcyan"))))
     (xxml-rug-face ((t (:background "cyan"))))
     (xxml-sparkle-face ((t (:background "yellow"))))
     (xxml-unbreakable-space-face ((t (:foreground "grey" :underline t))))
     (zmacs-region ((t (:background "#5d5d5d")))))))

;;; Eliminate bold fonts entirely
(mapc
 (lambda (face)
	(when (eq (face-attribute face :weight) 'bold)
	  (set-face-attribute face nil :weight 'normal)))
 (face-list))

(add-to-list 'color-themes '(color-theme-darkgray  "Dark Gray" "Chris McMahan <cmcmahan@one.net>") t)
